<?php
// Test script for login notification emails
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mailer\Mailer;

// Email to send the test to - replace with your actual email
$emailTo = 'hala.omran@jameiconseil.org';

// Create direct SMTP transport with detailed configuration
$transport = new EsmtpTransport(
    'smtp.hostinger.com',    // SMTP host
    465,                     // Port
    true                     // Use SSL
);
$transport->setUsername('hala.omran@jameiconseil.org');
$transport->setPassword('Oussama1981@');

// Create the mailer with our transport
$mailer = new Mailer($transport);

// Generate a more direct password reset link
$resetUrl = 'https://127.0.0.1:8000/reset-password-request'; // This would normally be generated by the ResetPasswordService

// Generate login notification HTML
$html = getLoginNotificationTemplate('Test User', new DateTime(), '127.0.0.1', 'Desktop - Windows - Chrome', $resetUrl);

// Create the email
$email = (new Email())
    ->from(new Address('hala.omran@jameiconseil.org', 'TripMakers Security'))
    ->to($emailTo)
    ->subject('Test: New login to your TripMakers account')
    ->html($html);

try {
    // Send the email
    $mailer->send($email);
    echo "Test login notification email sent successfully!\n";
} catch (\Exception $e) {
    echo "Failed to send login notification email: " . $e->getMessage() . "\n";
    echo "Error type: " . get_class($e) . "\n";
}

function getLoginNotificationTemplate(
    string $userName,
    \DateTime $loginTime,
    string $ipAddress,
    string $deviceInfo,
    string $resetUrl
): string {
    return <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Login Alert</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f5f7; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: #3554D1; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
        .header h1 { color: white; margin: 0; font-size: 24px; }
        .content { background-color: #ffffff; padding: 30px; border-radius: 0 0 8px 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .footer { text-align: center; margin-top: 20px; color: #6c757d; font-size: 12px; }
        .btn { display: inline-block; background-color: #3554D1; color: white; text-decoration: none; padding: 12px 25px; border-radius: 25px; margin: 15px 0; font-weight: bold; }
        .btn-warning { background-color: #dc3545; }
        .highlight { font-weight: bold; color: #3554D1; }
        .warning { color: #dc3545; font-weight: bold; }
        .login-details { background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #3554D1; }
        .login-details p { margin: 5px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>New Login Alert</h1>
        </div>
        <div class="content">
            <p>Hello <span class="highlight">{$userName}</span>,</p>
            <p>We detected a <strong>new login</strong> to your TripMakers account. If this was you, you can safely ignore this email.</p>
            
            <div class="login-details">
                <p><strong>Time:</strong> {$loginTime->format('F j, Y, g:i a')}</p>
                <p><strong>IP Address:</strong> {$ipAddress}</p>
                <p><strong>Device:</strong> {$deviceInfo}</p>
            </div>
            
            <p class="warning">If you didn't login recently, your account may have been compromised.</p>
            <p>To secure your account, you should immediately:</p>
            <p style="text-align: center;">
                <a href="{$resetUrl}" class="btn btn-warning">Reset Your Password</a>
            </p>
            <p style="font-size: 12px; color: #666; text-align: center; margin-top: 5px;">Click the button above to immediately change your password</p>
        </div>
        <div class="footer">
            <p>&copy; {$loginTime->format('Y')} TripMakers. All rights reserved.</p>
            <p>This is an automated security message from TripMakers. Please do not reply to this email.</p>
        </div>
    </div>
</body>
</html>
HTML;
}
