#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_reset_password_request:
    path: /reset-password-request
    controller: App\Controller\ResetPasswordController::request

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset
